### ISSUE TITLE
SNOW-938294: authenticator = "externalbrowser" triggers a login after every snowcli command

### ISSUE THREAD

**Issue by sfc-gh-asaini** [Snowflake-Labs/snowcli#475]
### SnowCLI version

1.2.0

### Python version

3.8.15

### Platform

MacOS

### What happened

Here is my `config.toml`

```toml
[connections]

[options]
default_connection = "pm"

[connections.pm]
account = "pm"
user = "asaini"
authenticator = "externalbrowser"
warehouse = "hlevel1"
database = "local_demo"
schema = "local_schema"
```

For every command that I run, snowcli triggers a fresh login. This makes for an unpleasant experience. 

Ideally, we should make the user login only once. Upon login all commands should run on the shell directly

cc: @sfc-gh-anugupta
