### ISSUE TITLE
snow streamlit deploy fails if a file not in a folder is in additional_source_files

### ISSUE THREAD

**Issue by sfc-gh-zblackwood** [Snowflake-Labs/snowcli#577]
### SnowCLI version

SnowCLI Version: 2.0.0-alpha.1

### Python version

Python 3.8.12

### Platform

macOS-14.1.1-arm64-arm-64bit

### What happened

`snow streamlit deploy` fails with this snowflake.yml
```yaml
definition_version: 1
streamlit:
  name: name
  query_warehouse: warehouse
  stage: stage
  main_file: streamlit_app.py
  env_file: environment.yml
  pages_dir: pages/
  additional_source_files:
    - other_file.py
```    

### Console output

```Shell
2023-11-29 13:49:42 DEBUG [snowcli.cli.common.sql_execution] Executing put file://other_file.py snow://streamlit/PATH/default_checkout/. auto_compress=false parallel=4 overwrite=True

253003: While putting file(s) there was an error: 'HTTPError('403 Client Error: Forbidden for url: https://.../checkouts/.../other_file.py')', this might be caused by your access to the blob storage provider, or by Snowflake.
```

### How to reproduce

create snowflake.yml with a file not in a folder in additional_source_files, and do `snow streamlit deploy`
