### ISSUE TITLE
SNOW-1022985: Snowpark optional arguments: passing non-empty list as a default value causes parsing error

### ISSUE THREAD

**Issue by sfc-gh-pczajka** [Snowflake-Labs/snowcli#706]
### SnowCLI version

SnowCLI Version: 2.0.0rc0

### Python version

3.11

### What happened

Detected during manual tests of https://github.com/Snowflake-Labs/snowcli/pull/701
Looks like bug in parsing project definition

### Console output

```Shell
▶ cat snowflake.yml
definition_version: 1
snowpark:
  project_name: "my_snowpark_project"
  stage_name: "dev_deployment"
  src: "app/"
  functions:
    - name: debug_f
      handler: "functions.debug_function"
      signature:
        - name: "l"
          type: array
          default: "[1, 2, 3]"
        - name: "s"
          type: "string"
          default: "<str>"
        - name: "i"
          type: "int"
          default: "7"
        - name: "b"
          type: "boolean"
          default: "True"
        - name: "f"
          type: "float"
          default: "1.5"
      returns: string

▶ snow snowpark deploy --debug
2024-01-30 14:14:25 DEBUG [snowflake.cli.api.sql_execution] Executing show integrations
...

│ /Users/pczajka/Snowflake/snowcli/src/snowflake/cli/plugins/snowpark/commands.py:174 in           │
│ _find_existing_objects                                                                           │
│                                                                                                  │
│   171 │   │   try:                                                                               │
│   172 │   │   │   current_state = om.describe(                                                   │
│   173 │   │   │   │   object_type=object_type.value.sf_name,                                     │
│ ❱ 174 │   │   │   │   name=remove_parameter_names(identifier),                                   │
│   175 │   │   │   )                                                                              │
│   176 │   │   │   existing_objects[identifier] = current_state                                   │
│   177 │   │   except ProgrammingError:                                                           │
│                                                                                                  │
│ /Users/pczajka/Snowflake/snowcli/src/snowflake/cli/plugins/snowpark/common.py:27 in              │
│ remove_parameter_names                                                                           │
│                                                                                                  │
│    24 │   parameters = identifier[open_parenthesis_index + 1 : -1]                               │
│    25 │   if not parameters:                                                                     │
│    26 │   │   return identifier                                                                  │
│ ❱  27 │   types = [t.strip().split(" ")[1] for t in parameters.split(",")]                       │
│    28 │   return f"{identifier[0:open_parenthesis_index]}({', '.join(types)})"                   │
│    29                                                                                            │
│    30                                                                                            │
│                                                                                                  │
│ /Users/pczajka/Snowflake/snowcli/src/snowflake/cli/plugins/snowpark/common.py:27 in <listcomp>   │
│                                                                                                  │
│    24 │   parameters = identifier[open_parenthesis_index + 1 : -1]                               │
│    25 │   if not parameters:                                                                     │
│    26 │   │   return identifier                                                                  │
│ ❱  27 │   types = [t.strip().split(" ")[1] for t in parameters.split(",")]                       │
│    28 │   return f"{identifier[0:open_parenthesis_index]}({', '.join(types)})"                   │
│    29                                                                                            │
│    30                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: list index out of range
```

### How to reproduce

snowflake.yml:
```yml
definition_version: 1
snowpark:
  project_name: "my_snowpark_project"
  stage_name: "dev_deployment"
  src: "app/"
  functions:
    - name: debug_f
      handler: "functions.debug_function"
      signature:
        - name: "l"
          type: array
          default: "[1, 2, 3]"
        - name: "s"
          type: "string"
          default: "<str>"
        - name: "i"
          type: "int"
          default: "7"
        - name: "b"
          type: "boolean"
          default: "True"
        - name: "f"
          type: "float"
          default: "1.5"
      returns: string
   ```   
  app/functions.py:
  ```py
from __future__ import annotations


def debug_function(l: List[int], s: str, i: int, b: bool, f: float) -> str:
    return f"s:{s} i:{i} b:{b} f:{f} l:{l}"
  ```
